name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.2
  easy_video_editor: ^0.1.1
  path_provider: ^2.1.5
  deepgram_speech_to_text: ^4.0.0
  http: ^1.5.0
  intl: ^0.19.0
  clipboard: ^2.0.2
  states_rebuilder: ^6.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
